name: PROS build

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ARM Toolchain
        uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4'

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install click==6.7
          pip install pyserial
          pip install cachetools
          pip install requests
          pip install tabulate
          pip install jsonpickle
          pip install semantic-version
          pip install colorama
          pip install pyzmq
          pip install cobs
          pip install scan-build==2.0.13

      - name: Install PROS CLI
        run: pip install https://github.com/purduesigbots/pros-cli/releases/download/3.1.4/pros_cli_v5-3.1.4-py3-none-any.whl

      - name: Testing PROS Install 
        run: prosv5 --version

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build PROS Project  
        run: prosv5 make clean all
